### ISSUE TITLE
Use more efficient API for GitHub

### ISSUE THREAD

**Issue by smola** [src-d/identity-matching#61]
GitHub support currently uses the search API, but it could use other APIs with higher quotas. For example, given a commit, it could use the get commit API: [Get a single commit](https://developer.github.com/v3/repos/commits/#get-a-single-commit).

If I got it right, search is limited to 30 requests per minute (1800 per hour) and getting a commit should be 5000 per hour.

**Comment by vmarkovtsev** [comment]
We are using the search API because we need to match the user's email to the user ID.
Changing the logic to querying distinct commits will result in rewriting 100% of the current external matching code. It will not be trivial - we will have to spell dark magic to determine the unique commits for each email - and I estimate the implementation to take 1-2 months given 0.5 people working on the project right now.

Let's close this for now.

**Comment by smola** [comment]
@vmarkovtsev Here's a PoC https://github.com/src-d/identity-matching/pull/63

It has a few gotchas but I think it can be done quite cleanly with some changes I described in the draft pull request.

**Comment by vmarkovtsev** [comment]
Done
